package Vistas.VIEWS;
import Conexión.Conexión;
import Modelo.Hotel;
import dao.HotelDAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


public class FormularioHotel extends javax.swing.JDialog {
    
private boolean esEdicion = false;
private int idHotelEnEdicion = -1;
private GestionHotel gestionHotel;



public void setModoEdicion(boolean esEdicion, Hotel hotel) {
    this.esEdicion = esEdicion;
    if (hotel != null) {
        this.idHotelEnEdicion = hotel.getIdHotel();
        txtNombreHotel.setText(hotel.getNombreHotel());
        txtDescripcionHotel1.setText(hotel.getDescripcion());
        txtDireccionHotel.setText(hotel.getDireccion());
        jComboBoxCategoria.setSelectedItem(hotel.getCategoria());
        jComboBoxEstado.setSelectedItem(hotel.getEstado());

        // Buscar y seleccionar proveedor en el combo
        for (int i = 0; i < jComboBoxProveedor.getItemCount(); i++) {
            ProveedorItem item = (ProveedorItem) jComboBoxProveedor.getItemAt(i);
            if (item.getId() == hotel.getIdProveedor()) {
                jComboBoxProveedor.setSelectedIndex(i);
                break;
            }
        }
    }
}




    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormularioHotel.class.getName());
    
    class ProveedorItem {
    private int id;
    private String nombre;

    public ProveedorItem(int id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }

    public int getId() {
        return id;
    }

    @Override
    public String toString() {
        return nombre; // Esto se mostrará en el ComboBox
    }
}
    /**
     * Constructor del formulario de registro de hoteles.
     * @param parent El frame padre de esta ventana.
     * @param modal Indica si el diálogo es modal o no.
     */
    public FormularioHotel(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarProveedores();
    }
    

    public void setGestionHotel(GestionHotel gestionHotel) {
        this.gestionHotel = gestionHotel;
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        btnConfiguracion2 = new javax.swing.JButton();
        btnHome2 = new javax.swing.JButton();
        btnClientes2 = new javax.swing.JButton();
        btnReservas2 = new javax.swing.JButton();
        btnProveedores2 = new javax.swing.JButton();
        btnReportes2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreHotel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDescripcionHotel1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDireccionHotel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxEstado = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxProveedor = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(null);

        btnConfiguracion2.setBackground(new java.awt.Color(0, 46, 121));
        btnConfiguracion2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnConfiguracion2.setForeground(new java.awt.Color(255, 255, 255));
        btnConfiguracion2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-config-23 (1).png"))); // NOI18N
        btnConfiguracion2.setText(" CONFIGURACIÓN");
        btnConfiguracion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiguracion2ActionPerformed(evt);
            }
        });
        jPanel6.add(btnConfiguracion2);
        btnConfiguracion2.setBounds(-10, 330, 210, 50);

        btnHome2.setBackground(new java.awt.Color(0, 46, 121));
        btnHome2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnHome2.setForeground(new java.awt.Color(255, 255, 255));
        btnHome2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-house-23.png"))); // NOI18N
        btnHome2.setText(" HOME");
        btnHome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome2ActionPerformed(evt);
            }
        });
        jPanel6.add(btnHome2);
        btnHome2.setBounds(-10, 80, 210, 50);

        btnClientes2.setBackground(new java.awt.Color(0, 46, 121));
        btnClientes2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnClientes2.setForeground(new java.awt.Color(255, 255, 255));
        btnClientes2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-customers-23.png"))); // NOI18N
        btnClientes2.setText(" CLIENTES");
        btnClientes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientes2ActionPerformed(evt);
            }
        });
        jPanel6.add(btnClientes2);
        btnClientes2.setBounds(-10, 130, 210, 50);

        btnReservas2.setBackground(new java.awt.Color(0, 46, 121));
        btnReservas2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnReservas2.setForeground(new java.awt.Color(255, 255, 255));
        btnReservas2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-calendar-23.png"))); // NOI18N
        btnReservas2.setText(" RESERVAS");
        btnReservas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservas2ActionPerformed(evt);
            }
        });
        jPanel6.add(btnReservas2);
        btnReservas2.setBounds(-10, 180, 210, 50);

        btnProveedores2.setBackground(new java.awt.Color(0, 46, 121));
        btnProveedores2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnProveedores2.setForeground(new java.awt.Color(255, 255, 255));
        btnProveedores2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-supplier-23.png"))); // NOI18N
        btnProveedores2.setText(" PROVEEDORES");
        btnProveedores2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedores2ActionPerformed(evt);
            }
        });
        jPanel6.add(btnProveedores2);
        btnProveedores2.setBounds(-10, 230, 210, 50);

        btnReportes2.setBackground(new java.awt.Color(0, 46, 121));
        btnReportes2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnReportes2.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-report-23 (1).png"))); // NOI18N
        btnReportes2.setText(" REPORTES");
        btnReportes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportes2ActionPerformed(evt);
            }
        });
        jPanel6.add(btnReportes2);
        btnReportes2.setBounds(-10, 280, 210, 50);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("FORMULARIO DEL HOTEL");
        jPanel6.add(jLabel8);
        jLabel8.setBounds(450, 130, 206, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nombre:");
        jPanel6.add(jLabel2);
        jLabel2.setBounds(330, 170, 60, 17);

        txtNombreHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreHotelActionPerformed(evt);
            }
        });
        jPanel6.add(txtNombreHotel);
        txtNombreHotel.setBounds(330, 190, 222, 38);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Descripción:");
        jPanel6.add(jLabel3);
        jLabel3.setBounds(330, 260, 75, 20);

        txtDescripcionHotel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionHotel1ActionPerformed(evt);
            }
        });
        jPanel6.add(txtDescripcionHotel1);
        txtDescripcionHotel1.setBounds(330, 280, 278, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Direccion:");
        jPanel6.add(jLabel4);
        jLabel4.setBounds(330, 350, 61, 17);

        txtDireccionHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionHotelActionPerformed(evt);
            }
        });
        jPanel6.add(txtDireccionHotel);
        txtDireccionHotel.setBounds(330, 370, 278, 35);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Categoria:");
        jPanel6.add(jLabel5);
        jLabel5.setBounds(670, 170, 63, 17);

        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Estrella", "2  Estrella", "3  Estrella", "4  Estrella", "5  Estrella" }));
        jComboBoxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoriaActionPerformed(evt);
            }
        });
        jPanel6.add(jComboBoxCategoria);
        jComboBoxCategoria.setBounds(670, 190, 97, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Estado:");
        jPanel6.add(jLabel6);
        jLabel6.setBounds(670, 260, 47, 17);

        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Desactivo" }));
        jComboBoxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEstadoActionPerformed(evt);
            }
        });
        jPanel6.add(jComboBoxEstado);
        jComboBoxEstado.setBounds(670, 280, 85, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Id Provedor:");
        jPanel6.add(jLabel7);
        jLabel7.setBounds(670, 350, 78, 17);

        jComboBoxProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProveedorActionPerformed(evt);
            }
        });
        jPanel6.add(jComboBoxProveedor);
        jComboBoxProveedor.setBounds(670, 370, 72, 30);

        btnGuardar.setBackground(new java.awt.Color(40, 167, 69));
        btnGuardar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel6.add(btnGuardar);
        btnGuardar.setBounds(580, 480, 160, 30);

        btnLimpiar.setBackground(new java.awt.Color(153, 153, 153));
        btnLimpiar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel6.add(btnLimpiar);
        btnLimpiar.setBounds(400, 480, 160, 30);

        jTextField2.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(204, 204, 204)));
        jPanel6.add(jTextField2);
        jTextField2.setBounds(300, 120, 510, 350);

        jPanel2.setBackground(new java.awt.Color(0, 46, 121));

        jButton7.setBackground(new java.awt.Color(179, 23, 23));
        jButton7.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Cerrar sesión");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(8, 8, 100));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" EXPRESO LOS CHANKAS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 356, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel2);
        jPanel2.setBounds(0, 0, 890, 80);

        jTextField1.setBackground(new java.awt.Color(0, 46, 121));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField1);
        jTextField1.setBounds(0, 340, 200, 210);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 888, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

/**
 * Constructor del formulario de registro de hoteles.
 * 
 * @param parent El frame padre de esta ventana.
 * @param modal Indica si el diálogo es modal o no.
 */

private void cargarProveedores() {
    try (Connection conn = Conexión.conectar();
         PreparedStatement stmt = conn.prepareStatement("SELECT ID_Proveedor, NombreProveedor FROM proveedor");
         ResultSet rs = stmt.executeQuery()) {

        while (rs.next()) {
            int id = rs.getInt("ID_Proveedor");
            String nombre = rs.getString("NombreProveedor");
            jComboBoxProveedor.addItem(new ProveedorItem(id, nombre));
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al cargar proveedores: " + e.getMessage());
    }
}

    
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
    txtNombreHotel.setText("");
    txtDireccionHotel.setText("");
    txtDescripcionHotel1.setText("");
    jComboBoxCategoria.setSelectedIndex(0);
    jComboBoxEstado.setSelectedIndex(0);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
    String nombre = txtNombreHotel.getText().trim();
    String descripcion = txtDescripcionHotel1.getText().trim();
    String direccion = txtDireccionHotel.getText().trim();
    String categoria = jComboBoxCategoria.getSelectedItem().toString();
    String estado = jComboBoxEstado.getSelectedItem().toString();

    if (nombre.isEmpty() || descripcion.isEmpty() || direccion.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Campos Vacíos", JOptionPane.WARNING_MESSAGE);
        return;
    }

    ProveedorItem proveedorSeleccionado = (ProveedorItem) jComboBoxProveedor.getSelectedItem();
    int idProveedor = proveedorSeleccionado.getId();
    int idDestino = 1; // Puedes modificarlo si usas jComboBoxDestino u otro valor

    HotelDAO hotelDAO = new HotelDAO();
    boolean exito;

    if (esEdicion && idHotelEnEdicion != -1) {
        Hotel hotelActualizado = new Hotel(idHotelEnEdicion, nombre, descripcion, direccion, categoria, estado, idDestino, idProveedor);
        exito = hotelDAO.actualizarHotel(hotelActualizado);
    } else {
        Hotel nuevoHotel = new Hotel(nombre, descripcion, direccion, categoria, estado, idDestino, idProveedor);
        exito = hotelDAO.insertarHotel(nuevoHotel);
    }

    if (exito) {
        JOptionPane.showMessageDialog(this, esEdicion ? "Hotel actualizado correctamente." : "Hotel registrado exitosamente.");

        // ✅ Refrescar tabla en GestionHotel si hay referencia
        if (gestionHotel != null) {
            gestionHotel.cargarHotelesEnTabla();
        }

        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Error al guardar el hotel.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtDireccionHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionHotelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionHotelActionPerformed

    private void jComboBoxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCategoriaActionPerformed

    private void jComboBoxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEstadoActionPerformed

    private void txtDescripcionHotel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionHotel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionHotel1ActionPerformed

    private void txtNombreHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreHotelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreHotelActionPerformed

    private void jComboBoxProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxProveedorActionPerformed

    private void btnConfiguracion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiguracion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfiguracion2ActionPerformed

    private void btnHome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome2ActionPerformed

    }//GEN-LAST:event_btnHome2ActionPerformed

    private void btnClientes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientes2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClientes2ActionPerformed

    private void btnReservas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservas2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReservas2ActionPerformed

    private void btnProveedores2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedores2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProveedores2ActionPerformed

    private void btnReportes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportes2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportes2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Desea cerrar sesión?", "Confirmación", JOptionPane.OK_CANCEL_OPTION);

        if (respuesta == JOptionPane.OK_OPTION) {
            this.dispose(); // Cierra la ventana actual
            new Login().setVisible(true); // Abre la ventana de login
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FormularioHotel dialog = new FormularioHotel(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes2;
    private javax.swing.JButton btnConfiguracion2;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnHome2;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnProveedores2;
    private javax.swing.JButton btnReportes2;
    private javax.swing.JButton btnReservas2;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JComboBox<String> jComboBoxEstado;
    private javax.swing.JComboBox<ProveedorItem> jComboBoxProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField txtDescripcionHotel1;
    private javax.swing.JTextField txtDireccionHotel;
    private javax.swing.JTextField txtNombreHotel;
    // End of variables declaration//GEN-END:variables

    void setModoEdicion(boolean b, Object object) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

}
